CODES SEGMENT
     ASSUME CS:CODES
START:MOV CX,5
      MOV DX,280H
NEXT: MOV AL,0FH
      OUT DX,AL
      CALL DELAY
	  MOV AL,00H
      OUT DX,AL
      CALL DELAY
	  LOOP NEXT
      MOV AH,4CH
      INT 21H
DELAY PROC NEAR
      PUSH CX
      MOV BX,299H
 FOR1:MOV CX,0FFFFH
 FOR2:LOOP FOR2
      DEC BX
      JNZ FOR1
      POP CX
      RET
DELAY ENDP
CODES ENDS
     END START 